int my_strlcpy(char *dest,char *src,int n);
char *my_strncpy(char *dest,char *src,int n);
char *my_strcpy(char *dest,char *src);
int my_strlen(char *str);
void my_print_array(char *src);
char *my_strcat(char *dest,char *src);
char *my_strncat(char *dest,char *src,int n);
int my_strcmp(char *s1,char *s2);
int my_strncmp(char *s1, char *s2,int n);
char *my_strstr(char *str1,char *str2);
char *my_strchr(char *str,char target);
int my_atoi( char *str);
double my_atof( char *str);
void *my_memset(void *src,int value,int len);
void *my_memcpy(void *dest,  void *src, int n);
char *is_leagl(char *src,char *start,char *end);
void reverse_char(char *src,int len);
void recursion_reverse_char(char *src,int len);
int word_len(char *src);
void word_reverse(char *src,int len);
char *itoa(unsigned int x,int scale,char *buf);